os: Visual Studio 2015

matrix:
  fast_finish: true

platform:
  - x86
  - x64

configuration:
  - Release

before_build:
  - git submodule update --init --recursive
  - python get_steinberg_sdk.py
  - choco upgrade cmake
  - set path=C:\Program Files\CMake\bin;%path%

build_script:
  - ps: .\build.ps1 -Verbose $env:PLATFORM $env:CONFIGURATION

after_build:
  - ps: 7z a Win-Plugins-$env:PLATFORM.zip .\CMakeBuild\$env:PLATFORM\*\Release\*.dll

artifacts:
  - path: Win-Plugins-$(PLATFORM).zip
    name: Win-Plugins-$(PLATFORM)
